movienager/accounts/urls.py
from django.urls import path

import accounts.views as views

urlpatterns = [
    path("", views.index, name="index"),
    path("admin_panel", views.admin_panel, name="admin-panel"),
    path("signup", views.SignUpView.as_view(), name="signup"),
    path("signin", views.SignInView.as_view(), name="signin"),
    path("logout", views.UserLogoutView.as_view(), name="logout"),
    path("user_management", views.UserManagementView.as_view(), name="user-management"),
    path(
        "admin_panel/user_management",
        views.AdminPanelUserMngView.as_view(),
        name="admin-panel-user-mng",
    ),
    path(
        "user_edit/<pk>",
        views.UserEditView.as_view(),
        name="user-edit",
    ),
    path(
        "user_delete/<pk>",
        views.UserDeleteView.as_view(),
        name="user-delete",
    ),
]

movienager/movienager/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from accounts.urls import urlpatterns as accounts_urls
from movies.urls import urlpatterns as movies_urls

urlpatterns = [
    path("admin/", admin.site.urls),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
] + accounts_urls \
    + movies_urls

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    ) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movienager/movies/urls.py
from django.urls import include, path, re_path

import movies.views as views

movie_urls = [
    path("", views.MoviesView.as_view(), name="movies"),
    path("add", views.MovieAddView.as_view(), name="movie-add"),
    re_path(r"^edit/(?P<pk>\d+)$", views.MovieEditView.as_view(), name="movie-edit"),
    re_path(r"^delete/(?P<pk>\d+)$", views.MovieDeleteView.as_view(), name="movie-delete"),
]

person_urls = [
    path("", views.PeopleView.as_view(), name="people"),
    path("add", views.PersonAddView.as_view(), name="person-add"),
    re_path(r"^edit/(?P<pk>\d+)$", views.PersonEditView.as_view(), name="person-edit"),
    re_path(r"^delete/(?P<pk>\d+)$", views.PersonDeleteView.as_view(), name="person-delete"),
    re_path(r"^(?P<pk>\d+)$", views.PersonView.as_view(), name="person"),
]

urlpatterns = [
    path("movies/", include(movie_urls)),
    path("people/", include(person_urls)),
]

movienager/accounts/models.py
from django.contrib.auth.models import AbstractUser, Permission
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.contrib.contenttypes.models import ContentType
from django.db import models

from .managers import AdjustedUserManager


# Create your models here.
class User(AbstractUser):
    REGULAR_USER = 1
    ADMIN = 2
    TYPES = ((REGULAR_USER, "Regular user"), (ADMIN, "Admin"))

    username = models.CharField(
        max_length=30,
        unique=True,
        blank=True,
        null=True,
        help_text=("30 characters or fewer. Letters, digits and @/./+/-/_ only."),
        validators=[UnicodeUsernameValidator()],
        error_messages={"unique": ("A user with that username already exists."),},
    )
    first_name = models.CharField(max_length=20, blank=True)
    last_name = models.CharField(max_length=30, blank=True)
    email = models.EmailField(primary_key=True)
    photo = models.ImageField(blank=True, upload_to="profile_photos")
    user_type = models.PositiveSmallIntegerField(choices=TYPES, default=REGULAR_USER)

    objects = AdjustedUserManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        self.set_permission()

    def set_permission(self):
        if self.user_type == self.ADMIN:
            self.add_permission(self)
        else:
            self.remove_permission(self)

    @classmethod
    def get_permission(cls, user, perm_codename):
        content_type = ContentType.objects.get_for_model(cls)
        return Permission.objects.get(
            codename=perm_codename, content_type=content_type
        )

    def add_permission(self, user):
        permission = self.get_permission(self, "add_user")
        user.user_permissions.add(permission)

    def remove_permission(self, user):
        permission = self.get_permission(self, "add_user")
        user.user_permissions.remove(permission)

movienager/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from accounts.models import User


class UserRegistrationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ("username", "email")


class UserEditForm(forms.ModelForm):
    password = forms.CharField(max_length=128, required=False)

    class Meta:
        model = User
        exclude = ("photo", "last_login", "date_joined", "user_permissions", "groups")
        widgets = {"email": forms.EmailInput(attrs={"readonly": "readonly"})}


class UserExtendedEditForm(forms.ModelForm):
    class Meta(UserEditForm.Meta):
        exclude = ("last_login", "groups", "date_joined")

    def save(self):
        self.instance = super().save()
        self.instance.set_permission()
        return self.instance

movienager/accounts/views.py
import json

from django.conf import settings
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.core.exceptions import MultipleObjectsReturned
from django.http import HttpResponse, QueryDict
from django.shortcuts import redirect, render
from django.urls import reverse
from django.views import generic

import accounts.forms as forms
from accounts.models import User


# Create your views here.
def index(request):
    return render(request, "index.html")


def admin_panel(request):
    return redirect("admin-panel-user-mng")


class SignUpView(generic.CreateView):
    form_class = forms.UserRegistrationForm
    template_name = "auth_forms/signup.html"
    success_url = "signin"


class SignInView(LoginView):
    template_name = "auth_forms/signin.html"
    redirect_authenticated_user = True


class UserLogoutView(LogoutView):
    next_page = "/"


class AddUserRequired(PermissionRequiredMixin):
    login_url = "signin"
    permission_required = "accounts.add_user"


class AdminPanelUserMngView(AddUserRequired, generic.ListView):
    model = User
    context_object_name = "users"
    template_name = "user_management/admin-panel-user-mng.html"


class UserEditView(AddUserRequired, generic.UpdateView):
    model = User
    template_name = "user_forms/user-edit.html"
    success_url = "/admin_panel/user_management"
    form_class = forms.UserExtendedEditForm


class UserDeleteView(AddUserRequired, generic.DeleteView):
    model = User
    template_name = "user_forms/user-delete.html"
    success_url = "/admin_panel/user_management"


class UserManagementView(AddUserRequired, generic.ListView):
    model = User
    context_object_name = "users"
    template_name = "user_management/user-management.html"
    extra_context = {"form": forms.UserEditForm, "choices": User.TYPES}

    def post(self, request, *args, **kwargs):
        try:
            user = User.objects.get(email=request.POST.get("email"))
        except MultipleObjectsReturned:
            return HttpResponse("You cannot change the e-mail.")

        form = forms.UserEditForm(request.POST, instance=user)
        if form.is_valid():
            user = form.save()
            user.set_permission()
        return HttpResponse("Edited")

movienager/accounts/templates/SB-admin-base.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>
  {% block title %}
  {% endblock title %}
  </title>

  <!-- Custom fonts for this template -->
  <link href="../static/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="../static/css/sb-admin-2.min.css" rel="stylesheet">

  <!-- Custom styles for this page -->
  <link href="../static/vendor/datatables/dataTables.bootstrap4.min.css" rel="stylesheet">

</head>

<body id="page-top">

  <!-- Page Wrapper -->
  <div id="wrapper">

    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

      <!-- Sidebar - Brand -->
      <a class="sidebar-brand d-flex align-items-center justify-content-center" href="/user_list">
        <div class="sidebar-brand-icon">
          <i class="fas fa-user-cog"></i>
        </div>
        <div class="sidebar-brand-text mx-3">Admin Panel</div>
      </a>

      <!-- Divider -->
      <hr class="sidebar-divider my-0">

      <!-- Nav Item - Dashboard -->
      <li class="nav-item">
        <a class="nav-link" href="/user_list">
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span>Dashboard</span></a>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider">

      <!-- Heading -->
      <div class="sidebar-heading">
        Go to
      </div>

      <!-- Nav Item - Pages Collapse Menu -->
      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="true" aria-controls="collapsePages">
          <i class="fas fa-fw fa-folder"></i>
          <span>Pages</span>
        </a>
        <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Auth Pages:</h6>
            <a class="collapse-item" href={% url 'signup' %}>Register</a>
            <div class="collapse-divider"></div>
            <h6 class="collapse-header">Other Pages:</h6>
            <a class="collapse-item" href={% url 'main-page' %}>Main page</a>
          </div>
        </div>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider d-none d-md-block">

      <!-- Sidebar Toggler (Sidebar) -->
      <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
      </div>

    </ul>
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

        <!-- Topbar -->
        <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

          <!-- Sidebar Toggle (Topbar) -->
          <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
            <i class="fa fa-bars"></i>
          </button>

          <!-- Topbar Search -->
          <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
            <div class="input-group">
              <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
              <div class="input-group-append">
                <button class="btn btn-primary" type="button">
                  <i class="fas fa-search fa-sm"></i>
                </button>
              </div>
            </div>
          </form>

          <!-- Topbar Navbar -->
          <ul class="navbar-nav ml-auto">

            <!-- Nav Item - Search Dropdown (Visible Only XS) -->
            <li class="nav-item dropdown no-arrow d-sm-none">
              <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-search fa-fw"></i>
              </a>
              <!-- Dropdown - Messages -->
              <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in" aria-labelledby="searchDropdown">
                <form class="form-inline mr-auto w-100 navbar-search">
                  <div class="input-group">
                    <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
                    <div class="input-group-append">
                      <button class="btn btn-primary" type="button">
                        <i class="fas fa-search fa-sm"></i>
                      </button>
                    </div>
                  </div>
                </form>
              </div>
            </li>

            <div class="topbar-divider d-none d-sm-block"></div>

            <!-- Nav Item - User Information -->
            <li class="nav-item dropdown no-arrow">
              <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ request.user.email }}</span>
                <img class="img-profile rounded-circle" src={% if request.user.photo %}{{ request.user.photo.url }}{% else %}""{% endif %}>
              </a>
              <!-- Dropdown - User Information -->
              <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                  <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                  Logout
                </a>
              </div>
            </li>

          </ul>

        </nav>
        <!-- End of Topbar -->

        <!-- Begin Page Content -->
        <div class="container-fluid">

        {% block content %}
        {% endblock content %}

        </div>
        <!-- /.container-fluid -->

      </div>
      <!-- End of Main Content -->

      <!-- Footer -->
      <footer class="sticky-footer bg-white">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span>Copyright &copy; Movienager 2020</span><br><br>
            <span>Admin panel powered by SB Admin 2</span>
          </div>
        </div>
      </footer>
      <!-- End of Footer -->

    </div>
    <!-- End of Content Wrapper -->

  </div>
  <!-- End of Page Wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Logout</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Are you sure you want to log out?</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <a class="btn btn-primary" href={% url 'logout' %}>Logout</a>
        </div>
      </div>
    </div>
  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="../static/vendor/jquery/jquery.min.js"></script>
  <script src="../static/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  <!-- Core plugin JavaScript-->
  <script src="../static/vendor/jquery-easing/jquery.easing.min.js"></script>

  <!-- Custom scripts for all pages-->
  <script src="../static/js/sb-admin-2.min.js"></script>

  <!-- Page level plugins -->
  <script src="../static/vendor/datatables/jquery.dataTables.min.js"></script>
  <script src="../static/vendor/datatables/dataTables.bootstrap4.min.js"></script>

  <!-- Page level custom scripts -->
  <script src="../static/js/demo/datatables-demo.js"></script>

</body>

</html>

movienager/accounts/templates/admin-panel-base.html
{% extends 'auth-base.html' %}

  {% block additional_styling %}
   <!-- Custom styles for this page -->
  <link href="../static/vendor/datatables/dataTables.bootstrap4.min.css" rel="stylesheet">
  {% endblock additional_styling %}

{% block body %}

<body id="page-top">

  <!-- Page Wrapper -->
  <div id="wrapper">

    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

      <!-- Sidebar - Brand -->
      <a class="sidebar-brand d-flex align-items-center justify-content-center" href="/user_list">
        <div class="sidebar-brand-icon">
          <i class="fas fa-user-cog"></i>
        </div>
        <div class="sidebar-brand-text mx-3">Admin Panel</div>
      </a>

      <!-- Divider -->
      <hr class="sidebar-divider my-0">

      <!-- Nav Item - Dashboard -->
      <li class="nav-item">
        <a class="nav-link" href="/user_list">
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span>Dashboard</span></a>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider">

      <!-- Heading -->
      <div class="sidebar-heading">
        Go to
      </div>

      <!-- Nav Item - Pages Collapse Menu -->
      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="true" aria-controls="collapsePages">
          <i class="fas fa-fw fa-folder"></i>
          <span>Pages</span>
        </a>
        <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Auth Pages:</h6>
            <a class="collapse-item" href={% url 'signup' %}>Register</a>
            <div class="collapse-divider"></div>
            <h6 class="collapse-header">Other Pages:</h6>
            <a class="collapse-item" href={% url 'main-page' %}>Main page</a>
          </div>
        </div>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider d-none d-md-block">

      <!-- Sidebar Toggler (Sidebar) -->
      <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
      </div>

    </ul>
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

        <!-- Topbar -->
        <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

          <!-- Sidebar Toggle (Topbar) -->
          <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
            <i class="fa fa-bars"></i>
          </button>

          <!-- Topbar Search -->
          <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
            <div class="input-group">
              <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
              <div class="input-group-append">
                <button class="btn btn-primary" type="button">
                  <i class="fas fa-search fa-sm"></i>
                </button>
              </div>
            </div>
          </form>

          <!-- Topbar Navbar -->
          <ul class="navbar-nav ml-auto">

            <!-- Nav Item - Search Dropdown (Visible Only XS) -->
            <li class="nav-item dropdown no-arrow d-sm-none">
              <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-search fa-fw"></i>
              </a>
              <!-- Dropdown - Messages -->
              <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in" aria-labelledby="searchDropdown">
                <form class="form-inline mr-auto w-100 navbar-search">
                  <div class="input-group">
                    <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
                    <div class="input-group-append">
                      <button class="btn btn-primary" type="button">
                        <i class="fas fa-search fa-sm"></i>
                      </button>
                    </div>
                  </div>
                </form>
              </div>
            </li>

            <div class="topbar-divider d-none d-sm-block"></div>

            <!-- Nav Item - User Information -->
            <li class="nav-item dropdown no-arrow">
              <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ request.user.email }}</span>
                <img class="img-profile rounded-circle" src={% if request.user.photo %}{{ request.user.photo.url }}{% else %}""{% endif %}>
              </a>
              <!-- Dropdown - User Information -->
              <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                  <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                  Logout
                </a>
              </div>
            </li>

          </ul>

        </nav>
        <!-- End of Topbar -->

        <!-- Begin Page Content -->
        <div class="container-fluid">

        {% block content %}
        {% endblock content %}

        </div>
        <!-- /.container-fluid -->

      </div>
      <!-- End of Main Content -->

      <!-- Footer -->
      <footer class="sticky-footer bg-white">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span>Copyright &copy; Movienager 2020</span><br><br>
            <span>Admin panel powered by SB Admin 2</span>
          </div>
        </div>
      </footer>
      <!-- End of Footer -->

    </div>
    <!-- End of Content Wrapper -->

  </div>
  <!-- End of Page Wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Logout</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Are you sure you want to log out?</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <a class="btn btn-primary" href={% url 'logout' %}>Logout</a>
        </div>
      </div>
    </div>
  </div>

  {% include 'partials/auth-scripts.html' %}

  <!-- Page level plugins -->
  <script src="../static/vendor/datatables/jquery.dataTables.min.js"></script>
  <script src="../static/vendor/datatables/dataTables.bootstrap4.min.js"></script>

  <!-- Page level custom scripts -->
  <script src="../static/js/demo/datatables-demo.js"></script>

</body>

{% endblock body %}

movienager/accounts/templates/login.html
{% extends 'register.html' %}

{% load widget_tweaks %}

{% block title %}
  Sign in
{% endblock title %}

{% block form_title %}
  Sign in
{% endblock form_title %}

{% block form_content %}
  <div class="form-group">
    {% render_field form.username class="form-control form-control-user" placeholder="E-mail" %}
    <small class="form-text text-muted">{{ form.username.help_text }}</small>
  </div>
  <div class="form-group">
    {% render_field form.password class="form-control form-control-user" placeholder="Password" %}
    <small class="form-text text-muted">{{ form.password.help_text }}</small>
  </div>
{% endblock form_content %}

{% block button_name %}
  Sign in
{% endblock button_name %}

{% block chng_form_link %}
  <a class="small" href={% url 'signup'%}>Create an account instead</a>
{% endblock chng_form_link %}

movienager/accounts/templates/sign-up.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}
    Sign up
{% endblock title %}

{% block body %}
    <section class="container">
        <form action="" method="POST" class="mt-4">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="mb-4 btn btn-outline-info">Submit</button>
        </form>
    </section>
{% endblock body %}

movienager/accounts/templates/user-list.html
{% extends 'admin-panel-base.html' %}

{% block title %}
  User management
{% endblock title %}

{% block content %}

  <!-- Page Heading -->
  <h1 class="h3 mb-2 text-gray-800">User management</h1>
  <p class="mb-4">Below you will find the list containing all the users in the database. 
  You can edit their data and delete them using buttons on the right side of the table. 
  Clicking the buttons will redirect you to a separate page where you can make changes (in the case of clicking an edit button) and confirm or discard your decision.</p>

  <!-- User table -->
  <div class="card shadow mb-4">
    <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">Users</h6>
    </div>
    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
          {% include 'partials/user-list-colnames.html' %}
          {% include 'partials/user-list-colnames.html' with tfoot=True %}
          <tbody>
            {% for user in users %}
            <tr>
              <td>{{ user.email }}</td>
              <td>{{ user.username }}</td>
              <td>{{ user.first_name }}</td>
              <td>{{ user.last_name }}</td>
              <td>{{ user.date_joined }}</td>
              <td>{{ user.is_staff }}</td>
              <td>{{ user.is_superuser }}</td>
              <td>{{ user.get_user_type_display }}</td>
              <td>{{ user.is_active }}</td>
              <td>{{ user.last_login }}</td>
              <td><a href="{% url 'user-edit' user.email %}"><button class="btn btn-outline-info">Edit</button></a></td>
              <td><a href="{% url 'user-delete' user.email %}"><button class="btn btn-outline-danger">Delete</button></a></td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>

{% endblock content %}

movienager/accounts/templates/user-management.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}
    User Management
{% endblock title %}

{% block body %}
    {% if error %}
        <p>{{ error }}</p>
    {% endif %}
    <table>
        {% include 'partials/user-list-colnames.html' with management_view=True %}
        <tbody>
            {% for user in users %}
                <form action="" method="POST">
                {% csrf_token %}
                <tr>
                    <td> {% render_field form.email value=user.email %} </td>
                    <td> {% render_field form.username value=user.username %} </td>
                    <td> {% render_field form.first_name value=user.first_name %} </td>
                    <td> {% render_field form.last_name value=user.last_name %} </td>
                    <td> {{ user.date_joined }} </td>
                    <td><input type="checkbox" name="is_staff" id="id_is_staff" {% if user.is_staff %}checked{% endif %}></td>
                    <td><input type="checkbox" name="is_superuser" id="id_is_superuser" {% if user.is_superuser %}checked{% endif %}></td>
                    <td>
                        <select name="user_type" id="id_user_type">
                            {% for choice in choices %}
                                <option value="{{ choice.0 }}" {% if user.user_type == choice.0 %}selected{% endif %}>{{ choice.1 }}</option>
                            {% endfor %}
                        </select>
                    </td>
                    <td><input type="checkbox" name="is_active" id="id_is_active" {% if user.is_active %}checked{% endif %}></td>
                    <td> {{ user.last_login }} </td>
                    <td> {% render_field form.password placeholder="Enter a new password." %} </td>
                    <td><button type="submit" name="edit">Save</button></td>
                    <td><button type="submit" name="delete">Delete</button></td>
                </tr>
                </form>
            {% endfor %}
        </tbody>
    </table>
{% endblock body %}